export const MAX_USERS_PER_SUB_SESSION = 10;

export const MOBILE_BREAKPOINT = 768;

export const SEND_MESSAGE_COOLDOWN_MS = 800;

export const MESSAGE_CONTENT_MAX_LENGTH = 2000;

export const MESSAGE_CONTENT_MAX_LENGTH_E2E = 12000;

export const USER_NAME_MAX_LENGTH = 30;

export const ROOM_CODE_LENGTH = 12;

export const ROOM_PASSWORD_MAX_LENGTH = 20;

export const SUBSESSION_NAME_MAX_LENGTH = 20;

export const SCREEN_SHARE_TOTAL_BUDGET_BPS = 4_000_000;
export const SCREEN_SHARE_MIN_PER_PEER_BPS = 250_000;
export const SCREEN_SHARE_MAX_FPS = 15;
export const SCREEN_SHARE_LOW_FPS = 8;
